name: s444421
on: [push]
jobs:
  s444421:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - uses: iterative/setup-cml@v1
      - name: Train and evaluate model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train_and_evaluate.py

          cat build_accuracy.txt >> report.md
          cml-publish builds_accuracy.jpg --md >> report.md
          cml-send-comment report.md